version: '3.8'

services:
  postgres:
    container_name: django_skeleton_postgres
    image: postgres:15.2-alpine
    ports:
      - '5433:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data
    env_file:
      - .env
    networks:
      - django_skeleton_network

  django:
    container_name: django_skeleton_application
    build:
        context: .
        dockerfile: docker/django/Dockerfile
    volumes:
      - .:/application
    env_file:
      - .env
    networks:
      - django_skeleton_network
    depends_on:
      - postgres

  nginx:
    container_name: django_skeleton_nginx
    build:
      context: .
      dockerfile: docker/nginx/Dockerfile
    ports:
      - '8000:80'
    volumes:
      - static:/application/static
    networks:
      - django_skeleton_network
    depends_on:
      - django

volumes:
  postgres_data:
  .:
  static:

networks:
  django_skeleton_network: